blockchainservice:
  baseUrl: https://api.blockchain.com/v3/exchange/tickers/
  headerName: "user-agent"
  headerValue: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
  headerBody: "parameter"
